# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# -------------------------
# Site Settings 
# -------------------------
baseurl: /jekyll-docs-all-in-one # does not include hostname
title: jekyll-docs-all-in-one

# -------------------------
# Language and Timezone
# -------------------------
lang: # the language of your site, default as "en"
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

# -------------------------
# Paginate
# -------------------------
paginate: 8
paginate_path: /page/page:num # don't change this unless for special need

# -------------------------
# Build
# -------------------------
exclude:
  - README.md
  - LICENSE
  - jekyll-*.gemspec
  - package-lock.json
  - package.json
  - /node_modules

# -------------------------
# Plugins
# -------------------------
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
